### PR TITLE
test: add config tests, fix bugs, improve error message for name

### LINKED ISSUE #24: Name validation and error messaging
We should validate the name field in package.json and if it is not a valid name for the podlet-server then log an informative message that describes what they need to do to fix it. Their options are:
* Fix the name field in package.json OR
* Keep package.json as is and set the config value for `app.name` instead.

`app.name` takes precedent but, if not set, falls back to the package json name field.

### PR DESCRIPTION
**Pull request by digitalsadhu**
This PR adds thorough test coverage of the config module and fixes the following bugs found during testing:
* scripts.ts now supported
* lazy.ts now supported
* fallback.ts now supported
* Fixes https://github.com/podium-lib/labs/issues/24

### CODE REVIEW

File: packages/fastify-podlet-server/lib/config.js [hunk 1]
```diff
@@ -73,7 +69,18 @@ export default async function configuration({ cwd = process.cwd() }) {
     config.loadFile(join(cwd, `${join("config", "hosts", host, "config")}.${env}.json`));
   }
 
+  // validate the name field of package.json
+  if (name === config.get("app.name") && !/^[a-z-]*$/.test(name)) {
+    throw new Error(`Name field in package.json was not usable as a default app name because it uses characters other than a-z and -.\nYou have 2 choices:\n1. Either set it to a different name using lower case letters and the - character\n2. keep it as is and define the app name in config.\nA good place for this is in /config/common.json\neg. { "app": { "name": "my-app-name-here" } }"`)
```
Comment (trygve-lie) [inline packages/fastify-podlet-server/lib/config.js:74]: Great. I like!
